### ISSUE TITLE
Long wait to stop

### ISSUE THREAD

**Issue by value2k** [kicumkicum/stupid-player#56]
After calling .stop() i need to wait 500ms - 1000ms for stop.

**Comment by projetoarduino** [comment]
Hi congratulations for the project.

I need some help with this.

I play and pause musics,  but when i use player.resume() i get this error

[../deps/mpg123/src/output/alsa.c:165] error: cannot open device default
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: open() failed: -1
    at Speaker._open (/root/node_modules/stupid-player/node_modules/speaker/index.js:168:11)
    at Speaker._write (/root/node_modules/stupid-player/node_modules/speaker/index.js:242:21)
    at doWrite (/root/node_modules/stupid-player/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/root/node_modules/stupid-player/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Speaker.Writable.write (/root/node_modules/stupid-player/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at write (/root/node_modules/stupid-player/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/root/node_modules/stupid-player/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at /root/node_modules/stupid-player/node_modules/readable-stream/lib/_stream_readable.js:600:7
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

**Comment by kicumkicum** [comment]
Hi @value2k. I found the problem and will soon make fix :)

**Comment by kicumkicum** [comment]
@value2k I fix it in v0.3.2
