### ISSUE TITLE
player.resume() fail

### ISSUE THREAD

**Issue by projetoarduino** [kicumkicum/stupid-player#57]
Hi congratulations for the project.

I need some help with this.

I play and pause musics, but when i use player.resume() i get this error

[../deps/mpg123/src/output/alsa.c:165] error: cannot open device default
events.js:141
throw er; // Unhandled 'error' event
^

Error: open() failed: -1
at Speaker._open (/root/node_modules/stupid-player/node_modules/speaker/index.js:168:11)
at Speaker._write (/root/node_modules/stupid-player/node_modules/speaker/index.js:242:21)
at doWrite (/root/node_modules/stupid-player/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:406:64)
at writeOrBuffer (/root/node_modules/stupid-player/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:395:5)
at Speaker.Writable.write (/root/node_modules/stupid-player/node_modules/speaker/node_modules/readable-stream/lib/_stream_writable.js:322:11)
at write (/root/node_modules/stupid-player/node_modules/readable-stream/lib/_stream_readable.js:623:24)
at flow (/root/node_modules/stupid-player/node_modules/readable-stream/lib/_stream_readable.js:632:7)
at /root/node_modules/stupid-player/node_modules/readable-stream/lib/_stream_readable.js:600:7
at nextTickCallbackWith0Args (node.js:419:9)
at process._tickCallback (node.js:348:13)

**Comment by kicumkicum** [comment]
Hi.
What OS and stupid-player version you use?

**Comment by projetoarduino** [comment]
Hi

Armbian / ARM H3 processor Kernel 3.4 / Nano pi NEO

**Comment by kicumkicum** [comment]
@projetoarduino how version stupid-player you use? How node.js and npm you use?

You use this board [nano pi h3](https://www.aliexpress.com/item/NanoPi-NEO-Open-Source-Allwinner-H3-Development-Board-Super-Raspberry-Pie-Quad-core-Cortex-A7/32818855903.html)?
If yes, how you connect accoustic to it?

**Comment by projetoarduino** [comment]
Hi @kicumkicum 
I use Version 0.3.1 , Node 4.2.6, NPM 3.5.2.
Yes i use exactly this board, i get sound by pin header see on this link

http://cholla.mmto.org/nano_pi/NEO_pinout-02.jpg

**Comment by kicumkicum** [comment]
@projetoarduino how long did the audio stand on the pause?

**Comment by projetoarduino** [comment]
10 seconds, 2 seconds , time is no matter.
